### ISSUE TITLE
Suggestions for adding preprocessing

### ISSUE THREAD

**Issue by OpusK** [eProsima/Micro-XRCE-DDS#6]
Hi,

I am using microRTPS to support [TurtleBot3 with ROS2](https://github.com/ROBOTIS-GIT/OpenCR/tree/feature-ros2-micrortps).
There are some topic issues (this has been mentioned in other issues) but it works well. Thank you for your teams.

I would like to make it even better. This is related to how the Arduino IDE is compiled.
Unfortunately, Arduino's compilation method does not have various options like make and cmake.
Therefore, it is difficult to use your repository as it is as a submodule.

Your code can separate the source files to build through cmake's options, but Arduino compiles all the source files in the entire folder.
In particular, there are examples and tests, and the client's transport profile.
So, as in the previous version, we want to disable header files and functions that are called from the source file through preprocessing.

Could you consider this part in the next release?

**Comment by julianbermudez** [comment]
Hi @OpusK,

Thanks for working with our products.

Our philosophy is to work with CMake and different flags (options) in order to configure the compilation.
All the compile options are collected in a config.h file auto-generated by CMake, but you can write your own config.h base on the auto-generated file and uncoupled the build system in the way.

In relation with the transport profile, we will add defines in platform-dependent sources.

**Comment by OpusK** [comment]
Hi, @julianbermudez 

I'm using it like you are talking about config.h. This is okay.

> In relation with the transport profile, we will add defines in platform-dependent sources.

Thanks!
But, I hope you also define the code in the [test folder](https://github.com/eProsima/micro-RTPS-client/tree/master/test) and the [example](https://github.com/eProsima/micro-RTPS-client/tree/master/examples) code.
Since Arduino compiles all the files (I can not optionally exclude some folders), I have to delete these folders, so I can not use your repository as a submodule as it is.
