### ISSUE TITLE
Any plan for a rmw_micrortps ?

### ISSUE THREAD

**Issue by astralien3000** [eProsima/Micro-XRCE-DDS#7]
Hello,

Since there is a rmw_fastrtps, is there any plan to create an official rmw_micrortps ?

Cheers !

**Comment by BorjaOuterelo** [comment]
Hi, @astralien3000.

We already have the first implementation of rmw_micrortps. It will be public in the following days along with the associated type support generators.

Besides that, micro-RTPS will not be any more called micro-RTPS it will become Micro XRCE-DDS, as it matches with the protocol used, XRCE-DDS, rather than RTPS.
Then rmw will also reflect that change in its name. This implementation will use the new Micro XRCE-DDS.

I will let you know as soon as we have it.

Best

**Comment by astralien3000** [comment]
Nice ! I'm looking forward to see that !

Best

**Comment by BorjaOuterelo** [comment]
Hi, @astralien3000.

I have just pushed a sample of rmw-microxrcedds (note the name change, as it using the last release of Micro XRCE-DDS)
There is also type support and demo packages along with a Micro XRCE-DDS Agent-based ROS 2 package.

You can find all the related packages on [https://github.com/microROS](https://github.com/microROS)

If you need assistance with it, please contact me.

With this, I will close this issue.
