### ISSUE TITLE
Some questions on security of micro-ros

### ISSUE THREAD

**Issue by vibnwis** [eProsima/Micro-XRCE-DDS#88]
Hi there,
From https://micro.ros.org/docs/overview/ROS_2_feature_comparison/, I read about the following items which quite unclear to my understanding.
1. Would someone please explain the concepts of "logging"? I read about "
Logging | ∗ | Could be available as part of the standard logging mechanism in principle but not supported by Micro-XRCE-DDS due to dynamic message size. To be checked …"

2. The other statement, "Security is not yet supported in the communication process between the Client and the Agent. However, the micro-ROS Agent can benefit from Fast DDS security capabilities during the creation of DDS entities. Roadmap: Implementation of security mechanisms in Micro XRCE-DDS are planned for future releases."
 Has this been implemented? if not, at what stage is it in? when it will be available? Sorry I would like to make a comment of the security of micro-ROS in my report. Hence, it would need to be accurate.

Thank you
vi

**Comment by pablogs9** [comment]
Hello:
1. ROS 2 internal layers have implemented some logging functionality using files, stdout, and DDS. In micro-ROS we have removed some of these functionalities in order to make a lighter runtime operation. In this sentence, we also mention dynamic memory, usually, when handling strings in the micro-ROS internal stack (`rcl`, `rcutils`...) dynamic memory is used, so in order to avoid it, logging has been disabled.
2. No security mechanism has been implemented in Micro XRCE-DDS. The [standard](https://www.omg.org/spec/DDS-XRCE/1.0/PDF) does not provide any security highlight beyond using "secured transport layers" such as TLS. Regarding the FastDDS security, you can find more information [here](https://fast-rtps.docs.eprosima.com/en/latest/fastdds/security/security.html).
